# Generated by Django 4.2.23 on 2025-08-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deploymentjob",
            name="old_cluster",
        ),
        migrations.RemoveField(
            model_name="deploymentjob",
            name="old_network",
        ),
    ]
