# Generated by Django 4.2.23 on 2025-07-10 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datacenter",
            name="admin",
        ),
        migrations.AddField(
            model_name="datacenter",
            name="admins",
            field=models.ManyToManyField(
                related_name="datacenters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
