# Generated by Django 4.2.23 on 2025-08-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_deploymentjob_old_cluster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymentjob",
            name="datacenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.datacenter"
            ),
        ),
    ]
