# Generated by Django 4.2.23 on 2025-07-17 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_datacenter_admin_datacenter_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="diskarray",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_use", "In Use"),
                    ("maintenance", "Maintenance"),
                    ("available", "Available"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_use", "In Use"),
                    ("maintenance", "Maintenance"),
                    ("available", "Available"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ServerDiskArrayMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("iscsi", "iSCSI"),
                            ("fibre", "Fibre Channel"),
                            ("nfs", "NFS"),
                            ("smb", "SMB"),
                            ("sas", "SAS"),
                            ("other", "Other"),
                        ],
                        default="iscsi",
                        max_length=10,
                    ),
                ),
                (
                    "mount_point",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "disk_array",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_links",
                        to="app.diskarray",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disk_array_links",
                        to="app.server",
                    ),
                ),
            ],
            options={
                "unique_together": {("server", "disk_array")},
            },
        ),
    ]
