# Generated by Django 4.2.23 on 2025-08-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_deploymentjob_datacenter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deploymentjob",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="deploymentjob",
            name="network",
        ),
    ]
