# Generated by Django 4.2.23 on 2025-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_user_mfa_enabled_user_totp_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
