# Generated by Django 4.2.23 on 2025-08-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_deploymentjob_cluster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymentjob",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.cluster",
            ),
        ),
        migrations.AddField(
            model_name="deploymentjob",
            name="network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.network",
            ),
        ),
    ]
