# Generated by Django 4.2.23 on 2025-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_deploymentjob_cluster_deploymentjob_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymentjob",
            name="minio_object",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deploymentjob",
            name="plan_output",
            field=models.TextField(blank=True, null=True),
        ),
    ]
