# Generated by Django 4.2.23 on 2025-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_deploymentjob_minio_object_deploymentjob_plan_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymentjob",
            name="vm_count",
            field=models.IntegerField(default=1),
        ),
    ]
